### ISSUE TITLE
SIG Software Supply Chain Onboarding Checklist

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#360]
SIG Software Supply Chain has been approved by CDF TOC recently. [0][1]
According to [the process](https://github.com/cdfoundation/toc/blob/master/GROUPS.md#sig-onboarding-checklist) documented in TOC repo, there are few things the community needs assistance with.

- [x] **Create GitHub repo**: proposed name for the GitHub repository is _sig-software-supply-chain_
- [x] **Create GitHub team for the sig**: proposed name for the GitHub team is _sig-software-supply-chain_
- [x] **Create slack channel**: we could either create a new channel or rename _#sig-security_ to _#sig-software-supply-chain_
- [x] **Create groups.io mailing list**: proposed name for the maillist is _sig-software-supply-chain@lists.cd.foundation_
- [x] **SIG co-chairs to get access to CDF calendar to modify events**
- [x] **Create SIG playlist on Youtube**
- [x] **Announcement blog post/press release**: this is already in progress with @zestyroxy 
- [x] **Recommend scheduling a podcast**: This can perhaps wait until things settle.

Additionally, should the new SIG directly start with **Bevy** so we could avoid dealing with migration from Zoomlater on as well as we could share our learnings with other SIGs once they start migrating?

[0] https://lists.cd.foundation/g/cdf-toc/topic/88911382
[1] https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit#

**Comment by fdegir** [comment]
@MarckK @micmarti85 @zestyroxy I have few proposals and a question for setting the logistics for the new SIG above and could do my best to help.

For example, I seem to have permission to create repository and team on GitHub under CDF organization. 
If you like, I could create the repo and the team.

**Comment by MarckK** [comment]
Hi @fdegir, If you have the permissions, please do go ahead and create the repo and team on GH under CDF org. 
Thank you!

Looking forward to being involved with SIG Software Supply Chain! 🎉

**Comment by fdegir** [comment]
Thanks @MarckK. 

Created [the repository](https://github.com/cdfoundation/sig-software-supply-chain) and [the team](https://github.com/orgs/cdfoundation/teams/sig-software-supply-chain) for the SIG.

**Comment by oleg-nenashev** [comment]
Created the Slack channel. I have no permissions to do anything else from the list

**Comment by zestyroxy** [comment]
I created the [YouTube playlist](https://www.youtube.com/playlist?list=PL2KXbZ9-EY9TT2rKSBv6-BUdKqsJg9rAL)
The podcast is on hold until further notice, but yes--it should be an episode when we start again.
Bevy will be ready soon.

I believe my colleague Michelle can help create the following two items:
1. Mailing List 
Should we pre-subscribe anyone to the mailing list (if so, please send me the emails).

2. CDF calendar access 
Send me emails for the co-chairs

**Comment by fdegir** [comment]
> I created the [YouTube playlist](https://www.youtube.com/playlist?list=PL2KXbZ9-EY9TT2rKSBv6-BUdKqsJg9rAL) The podcast is on hold until further notice, but yes--it should be an episode when we start again. Bevy will be ready soon.

Thanks @zestyroxy!

> 1. Mailing List
>    Should we pre-subscribe anyone to the mailing list (if so, please send me the emails).

I'll confirm this with the current members of the SIG and then share their mail addresses.

> 2. CDF calendar access
>    Send me emails for the co-chairs

I'll include this information in the mail I referred above.

**Comment by zestyroxy** [comment]
Bevy is ready! https://community.cd.foundation/ Login with your LF accounts and tell me who should be the SSCS Chapter leaders.

**Comment by fdegir** [comment]
The SIG is fully operational now. Thanks everyone who helped with it!
